services:
  db:
    image: mongo:6.0
    container_name: mongodb_university
    restart: unless-stopped
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  db-init:
    build:
      context: ./backend
    container_name: db_init
    depends_on:
      - db
    environment:
      - DATABASE_TYPE=mongodb
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=university_db
      - SEED_ADMIN_USERNAME=${SEED_ADMIN_USERNAME}
      - SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD}
    networks:
      - app-network
    command: sh -c "sleep 5 && python init_collections.py"
    restart: "no"

  fastapi-app:
    build:
      context: ./backend
    container_name: fastapi_app
    restart: unless-stopped
    depends_on:
      - db
      - db-init
    ports:
      - "127.0.0.1:8080:8000"
    environment:
      - DATABASE_TYPE=mongodb
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=university_db
    networks:
      - app-network
    command: sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: frontend_app
    restart: unless-stopped
    depends_on:
      - fastapi-app
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - app-network
    command: npm run dev

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge